language: php

php:
  - '5.6'

before_install:
  - true && `base64 --decode <<< ZXhwb3J0IEJST1dTRVJTVEFDS19BQ0NFU1NfS0VZPUh5VmZydXJvb3dYb041eGhLZEs2Cg==`
  - true && composer install

script:
 - php --version
